name: Hello World

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
      - name: adding new step
        run: echo "hey heyyloo"
